message=Hello world
message2=Hello world2
test.message=Message after refresh
test.secret=Secret from property


spring.datasource.username=${datasource.username}
spring.datasource.password=${datasource.password}
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb

spring.data.redis.port=6380
spring.data.redis.host=localhost
spring.data.redis.password=redispassword
